### ISSUE TITLE
Authorization not working with this code

### ISSUE THREAD

**Issue by specter96** [grafana/xk6-kerberos#42]
I kept getting HTTP 401 responses from this:
const res = http.get("http://http.example.com", { Authorization: session });
Changing it to 
const res = http.get("http://http.example.com", {"headers": {"Authorization": session }});
fixed the issue

**Comment by oleiade** [comment]
Assigning you @joanlopez as I believe you'll have much more context than me on this. Let me know if I can help 🙇

**Comment by joanlopez** [comment]
Sure, np! @oleiade Looks like it's the example in docs/README.md that's wrong. 

Is that what you mean @specter96? If so, do you want to contribute with the small fix (PR)?
Or do you prefer us to fix it?

Thanks anyway for reporting it! 🙌
