### ISSUE TITLE
INFO - How to authenticate using keytab file

### ISSUE THREAD

**Issue by Fernandoramas** [grafana/xk6-kerberos#44]
Hi team,
This might be an absurd question for you. 
In our use case its not possible to authenticate to services with user and pass approach. Is this extension compatible for adding a `krb5.keytab` file in the request?
If its the case, how we would implement it?
super thanks

**Comment by olegbespalov** [comment]
Hi @Fernandoramas !

Unfortunately, it seems like, currently, the extension [supports only the username & password approach](https://github.com/grafana/xk6-kerberos/blob/main/module.go#L96). However, it looks like the library `gokrb5` that we use under the hood [does support the `krb5.keytab`](https://github.com/grafana/gokrb5/blob/master/client/client.go#L46). So, the implementation is a matter of initializing a new client.

Right now, this is not our priority and isn't even on our radars, but if you want, you could contribute to the xk6-kerberos and implement this.

cc: @joanlopez if you have something to add 👍

**Comment by joanlopez** [comment]
Hey @olegbespalov,

I have not much to say beyond what you mentioned. I feel it shouldn't take much, but as you said, it is not planned. If you @Fernandoramas, or anyone else reaching this issue, wants to give it a try, I'll be happy to support them.

So far, I can only recommend taking a look at [this development environment for Kerberos](https://github.com/joanlopez/kerberos-devenv) that I used to develop the extension, and [the setup used in the CI to run E2E tests](https://github.com/grafana/xk6-kerberos/blob/main/.github/workflows/e2e-test.yml).

Bear in mind that we use our own fork of `gokrb5` (the one that Oleg pointed to above).

That's all!

**Comment by Fernandoramas** [comment]
Hi again team,
Its a real pity. I need to finish some urgent tasks before the end of the year before starting with this. In January i might start trying to do the development. 
Thanks a lot for the quick support.
